In [2]:
import pandas as pd
import numpy as np

1. Write a Python program to create and display a one-dimensional array-like object
containing an array of data using Pandas module.

In [3]:
array = pd.Series([1,2,3,4,5])
print(array)

0    1
1    2
2    3
3    4
4    5
dtype: int64

2. Write a Python program to convert a Panda module Series to Python list and it's type.

In [4]:
array = pd.Series([1,2,3,4,5])
print(array)
print(type(array))
list = array.tolist()
print(list)
print(type(list))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
[1, 2, 3, 4, 5]
<class 'list'>

3. Write a Python program to add, subtract, multiple and divide two Pandas Series

In [5]:
series1 = pd.Series([1,2,3,4,5])
series2 = pd.Series([6,7,8,9,10])
print("sum \n", series1 + series2)
print("sub \n", series1 - series2)
print("mul \n", series1 * series2)
print("div \n", series1 / series2)

sum
 0     7
1     9
2    11
3    13
4    15
dtype: int64
sub
 0   -5
1   -5
2   -5
3   -5
4   -5
dtype: int64
mul
 0     6
1    14
2    24
3    36
4    50
dtype: int64
div
 0    0.166667
1    0.285714
2    0.375000
3    0.444444
4    0.500000
dtype: float64

4. Write a Python program to get the powers of an array values element-wise

In [6]:
arr = np.arange(7)
print(np.power(arr,3))

[  0   1   8  27  64 125 216]

5. Write a Python program to create and display a DataFrame from a specified dictionary
data which has the index labels

In [7]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

Data_Frame = pd.DataFrame(exam_data,index=labels)
Data_Frame

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

6. Write a Python program to display a summary of the basic information about a
specified Data Frame and its data

In [8]:
Data_Frame = pd.DataFrame(exam_data,index=labels)
Data_Frame.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      10 non-null     object
 1   score     8 non-null      float64
 2   attempts  10 non-null     int64
 3   qualify   10 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes

7. Write a Python program to get the first 3 rows of a given DataFrame.
Sample Python dictionary data and list labels

In [9]:
Data_Frame.head(3)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes

8. Write a Python program to select the 'name' and 'score' columns from the following
DataFrame

In [10]:
Data_Frame[['name','score']]

        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0

9. Write a Python program to select the specified columns and rows from a given data
frame

In [11]:
Data_Frame.iloc[[1,3,5,6]][['name','score']]

      name  score
b     Dima    9.0
d    James    NaN
f  Michael   20.0
g  Matthew   14.5

10. Write a Python program to select the rows where the number of attempts in the
examination is greater than 2

In [12]:
attempts = Data_Frame['attempts']>2
Data_Frame[attempts]

      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes

11. Write a Python program to count the number of rows and columns of a DataFrame.
Sample data

In [13]:
print("number of columns " ,Data_Frame.columns.__len__())
print("number of rows " ,Data_Frame.index.__len__())

number of columns  4
number of rows  10

12. Write a Python program to select the rows where the score is missing

In [14]:
Data_Frame[Data_Frame['score'].isnull()]

    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no

13. Write a Python program to select the rows where number of attempts in the
examination is less than 2 and score greater than 15

In [15]:
Data_Frame[(Data_Frame['attempts']<2) & (Data_Frame['score']>15)]

    name  score  attempts qualify
j  Jonas   19.0         1     yes

14. Write a Python program to change the score in row 'd' to 11.5

In [16]:
Data_Frame.loc['d','score'] = 11.5
Data_Frame

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

15. Write a Python program to calculate the sum of the examination attempts by the
students

In [17]:
sum(Data_Frame['attempts'])

19

16. Write a Python program to calculate the mean score for each different student in
DataFrame

In [18]:
Data_Frame['score'].mean()

13.333333333333334

17. Write a Python program to append a new row 'k' to data frame with given values for
each column

In [19]:
new_row = {'name' : 'Suresh', 'score': 15.5, 'attempts': 1, 'qualify': "yes"}
Data_Frame.loc['k'] = new_row
print('appended : \n',Data_Frame)
Data_Frame = Data_Frame.drop('k')
print('original : \n',Data_Frame)

appended :
         name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
k     Suresh   15.5         1     yes
original :
         name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

18. Write a Python program to sort the DataFrame first by 'name' in descending order,
then by 'score' in ascending order

In [20]:
new_data = Data_Frame.sort_values(['name'])
new_data = Data_Frame.sort_values(['score'],ascending=False)
new_data

        name  score  attempts qualify
f    Michael   20.0         3     yes
j      Jonas   19.0         1     yes
c  Katherine   16.5         2     yes
g    Matthew   14.5         1     yes
a  Anastasia   12.5         1     yes
d      James   11.5         3      no
b       Dima    9.0         3      no
e      Emily    9.0         2      no
i      Kevin    8.0         2      no
h      Laura    NaN         1      no

19. Write a Python program to replace the 'qualify' column contains the values 'yes' and
'no' with True and False

In [30]:
newdf = Data_Frame.copy()
newdf['qualify'] = Data_Frame['qualify'].map({'yes':True,'no':False})
newdf

        name  score  attempts  qualify
a  Anastasia   12.5         1     True
b       Dima    9.0         3    False
c  Katherine   16.5         2     True
d      James   11.5         3    False
e      Emily    9.0         2    False
f    Michael   20.0         3     True
g    Matthew   14.5         1     True
h      Laura    NaN         1    False
i      Kevin    8.0         2    False
j      Jonas   19.0         1     True

20. Write a Python program to delete the 'attempts' column from the DataFrame

In [32]:
Data_Frame.drop('attempts',axis=1)

        name  score qualify
a  Anastasia   12.5     yes
b       Dima    9.0      no
c  Katherine   16.5     yes
d      James   11.5      no
e      Emily    9.0      no
f    Michael   20.0     yes
g    Matthew   14.5     yes
h      Laura    NaN      no
i      Kevin    8.0      no
j      Jonas   19.0     yes

21. Write a Python program to insert a new column in existing DataFrame

In [49]:
Rol_no = [1,2,3,4,5,6,7,8,9,10]
Data_Frame['Roll no.'] = Rol_no
Data_Frame

        name  score  attempts qualify  Roll no.
a  Anastasia   12.5         1     yes         1
b       Dima    9.0         3      no         2
c  Katherine   16.5         2     yes         3
d      James   11.5         3      no         4
e      Emily    9.0         2      no         5
f    Michael   20.0         3     yes         6
g    Matthew   14.5         1     yes         7
h      Laura    NaN         1      no         8
i      Kevin    8.0         2      no         9
j      Jonas   19.0         1     yes        10

22. Write a Python program to iterate over rows in a DataFrame

In [53]:
for i in Data_Frame.index:
    print(Data_Frame['name'][i])

Anastasia
Dima
Katherine
James
Emily
Michael
Matthew
Laura
Kevin
Jonas

23. Write a Python program to get list from DataFrame column headers

In [57]:
list_column_headers = Data_Frame.columns.tolist()
print(list_column_headers)

['name', 'score', 'attempts', 'qualify', 'Roll no.']